# Generated by Django 5.2.10 on 2026-02-28 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dindintrack', '0002_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='fechamento_fatura',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='vencimento_fatura',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
