# Generated by Django 5.2.10 on 2026-03-02 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dindintrack', '0003_alter_cartao_fechamento_fatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='metodo_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dindintrack.cartao'),
        ),
    ]
