# Generated by Django 5.2.10 on 2026-03-02 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dindintrack', '0004_transacao_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='metodo_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dindintrack.cartao'),
        ),
    ]
